# Generated by Django 5.2.4 on 2025-07-09 06:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('telegram_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegramClients.telegramclient')),
            ],
        ),
    ]
